### PR TITLE
Revision of image dereference

### PR DESCRIPTION
**Pull request by YaoTingYao**
Fix the issue with delayed image computation in RST format

### CODE REVIEW

**Comment by YaoTingYao** [comment]
Hi @tawoodard, thank you again for your excellent contribution to resolving the RCD delay issue. I've updated the related scripts based on your solution. Please review the PR and merge it at your convenience. Cheers!

**Comment by agcopenhaver** [comment]
Could we make sure we don't merge those .pyc files

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver, thanks so much for pointing this out! The .pyc files has been deleted.

**Comment by tawoodard** [comment]
Removed return of image objects from functions to reference sooner

When images are passed back as return objects from functions, their reference stays alive until they are deferenced.  It is cleaner to dereference them as soon as they are no longer needed and let them get cleaned up when a function is exited.  This is tied to the issue of raster files or rdc files not getting fully written until they are dereferenced.  Setting them to None also works, but since the image objects are not used in places where the functions were called from, it's cleaner not to return them at all.

**Pull request merged**
