### PR TITLE
Added Windows installer 

### PR DESCRIPTION
**Pull request by YaoTingYao**
1. Added Windows installer UDef-ARP_WINDOWS_2.08_setup.exe.
2. Added .gitattributes to simplify cloning and forking with Git LFS.

### CODE REVIEW

**Comment by YaoTingYao** [comment]
The file size of UDef-ARP_WINDOWS_setup.exe (396 MB) exceeds GitHub's free tier file size limit of 100 MB. To address this, we've uploaded the file using Git Large File Storage (Git LFS) 

[!IMPORTANT]
To successfully download UDef-ARP_WINDOWS_setup.exe, you must install `Git LFS` before cloning or forking the repository. Downloading the repository as a ZIP file will not include the actual executable due to the nature of Git LFS.

Follow these steps:

1. ***Install Git LFS: ***Refer to [Installing Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) for detailed instructions on how to download and install `Git LFS`.

2.  ***Clone or Fork the Repository:***Once Git LFS is installed, you can safely clone or fork the repository to access the complete UDef-ARP_WINDOWS_setup.exe file.

For additional details, please visit [About Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)

**Comment by agcopenhaver** [comment]
hi @YaoTingYao  - I wonder if we might actually put the executable under [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)?

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver, thanks for bringing this up! Moving executable to the releases is indeed a great idea. I am currently working on releases section and will include it. Cheers!

**Review by agcopenhaver — COMMENTED** [review]
Hi @YaoTingYao - I know this is ultimately a Clark Labs repo, but I'd like to strongly caution against directly including the executables in the repo for a few reasons. 

My primary concern is that we don't actually have the build script in this repo, and if contributors make contributions to the source without being able to recompile the source, the .exe will become divergent and not representative of the current state of the source. Either that, or they'll have to recompile the .exe any time a change is made, which gets onerous fast.

Of secondary concern is that this will cause the size of the repo to rapidly balloon if we have frequently changing large .exe files directly in the repository.

Could we perhaps investigate using Github's releases feature to do this instead? This would associate the .exe with a particular point in the repos history and allow us to publish a changelog between versions. And it doesn't have size limits, so no additional requirements would be necessary

**Comment by agcopenhaver** [comment]
> Hi @agcopenhaver, thanks for bringing this up! Moving executable to the releases is indeed a great idea. I am currently working on releases section and will include it. Cheers!

OK - thanks for listening. I posted my long form review seconds after you posted this. Thanks!

**Comment by YaoTingYao** [comment]
Absolutely, and thank you for your valuable feedback. Your point about the potential divergence between the source code and the executable (.exe) files is well taken. This is indeed a crucial consideration in open-source projects. 

Regarding the repository size concern, using Git Large File Storage (LFS) effectively addresses this issue. With Git LFS, the actual large .exe files are stored externally, while the repository only contains small pointer files. These pointer files are text files, usually just a few hundred bytes in size, ensuring that frequent updates to the .exe files do not significantly increase the repository's size.

Nonetheless, your suggestion to utilize Releases for managing exe offers systematic tracking of version changes is a great idea. I will close the current PR and transition the executable files to Releases section. Cheers!

**Comment by YaoTingYao** [comment]
Move executable file to Releases section.

**Pull request closed without merging**
